列表与数组的区别

In [2]:
import  time
import random
import numpy as np

a = []
for i in range(100000000):
    a.append(random.random())
t1 = time.time()
sum1 = sum(a)
t2 = time.time()

b = np.array(a)
t3 = time.time()
sum2 = sum(b)
t4 = time.time()
print(t2-t1,t4-t3)

7.739196062088013 7.905726194381714


In [ ]:
list1 =[1,2,3,4]
a = np.array(list1)
type(a)
print(list1)
print(a)

In [3]:
t3 = np.arange(0,5,1)
t3

array([0, 1, 2, 3, 4])

In [4]:
arr_list = [[1,2],[3,4],[5,6]]
two_arr = np.array(arr_list)
print(two_arr.size)
print(two_arr.shape)
print(two_arr.ndim)

6
(3, 2)
2


In [14]:
# 更改数组形状
four = np.array([[1,2,3],[4,5,6]])
four =four.reshape(3,2)
print(four)
five = four.reshape((6,))
print(five)
six = five.flatten()

print(six)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [15]:
f = np.array([random.random() for i in range(5)],dtype=np.float32)
print(f.itemsize)
print(f.dtype)
f1 = f.astype(np.float64)
print(f)

4
float32
[0.35350963 0.9879296  0.51410943 0.80025834 0.38653547]


In [17]:
t = np.arange(24).reshape(4,6)
t[1,:]=0
t[~(t>6)]=0
print(t)

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


三目运算符

In [ ]:
score = np.array([[80,88],[82,81],[75,81]])
res = np.where(score>80,True,False)
print(res)

In [26]:
t1 = np.arange(24,dtype=int).reshape(4,6)
t = t1.clip(10,18)
print(t)

[[10 10 10 10 10 10]
 [10 10 10 10 10 11]
 [12 13 14 15 16 17]
 [18 18 18 18 18 18]]


数组的添加、删除和去重

数组的append需要同维数

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(np.append(a,[[7,8,9]],axis=0))
print(np.append(a,[[5,5,5],[10,11,12]],axis=1))

insert 多了一个插入位置

In [34]:
a = np.array([[1,2],[4,5],[7,8]])
print(np.insert(a,3,[9,10],axis=0))

[[ 1  2]
 [ 4  5]
 [ 7  8]
 [ 9 10]]


删除 delete 需要给出位置

In [35]:
a = np.array([[1,2,3],[4,5,6]])
print(np.delete(a,1,axis=1))

[[1 3]
 [4 6]]


去重 unique

In [8]:
import numpy  as np
a = np.array([5,2,6,2,7,5,6,8,2,9])
t = np.unique(a)
print(t)
print("-"*50)
u,indices = np.unique(a,return_index=True)
# 去除后的数组下标
print(indices)
print("-"*50)
# 去除数组在原数组的下标位置
u,indices = np.unique(a,return_inverse=True)
print(indices)

[2 5 6 7 8 9]
--------------------------------------------------
[1 0 2 4 7 9]
--------------------------------------------------
[1 0 2 0 3 1 2 4 0 5]


numpy 进行科学计算

In [25]:
score = np.array([[80,88],[82,81],[75,81]])
res = np.max(score,axis=0)
print(res)
res = np.min(score,axis=1)
print(res)
# 第一个位置与第二个比较
result = np.maximum( [-2, -1, 0, 1, 2], 0 )
print(result)
print("-"*50)
result = np.maximum([-2, -1, 0, 1, 6], [1, 2, 3, 4, 5])
# 返回较大的数组
print(result)
print("-"*50)
# 求平均值
aver = np.mean(score,axis=0)
print(aver)
print("-"*50)

print("-"*50)
arr = np.array([[1,2,3], [4,5,6],[7,8,9]])
print(arr)
# 求前缀和
print("-"*50)
print(arr.cumsum(0))
# 求最小索引值
res = np.argmin(score,axis=0)
print(res)
# 方差，标准差
print("-"*50)
res = np.var(score,axis=0)
result = np.std(score,axis=0)
print(res,result)
# 极值
print("-"*50)
res = np.ptp(score,axis=0)
print(res)

[82 88]
[80 81 75]
[0 0 0 1 2]
--------------------------------------------------
[1 2 3 4 6]
--------------------------------------------------
[79.         83.33333333]
--------------------------------------------------
--------------------------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[2 1]
--------------------------------------------------
[ 8.66666667 10.88888889] [2.94392029 3.29983165]
--------------------------------------------------
[7 7]


数组拼接

In [56]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
res = np.concatenate((a,b),axis=0)
# 打印拼接的数组，沿0轴
# print(res)
print("-"*50)
print(np.concatenate((a,b),axis=1))
# 2、沿某轴堆叠
print("-"*50)

print(np.stack((a,b),axis=1))

print("-"*50)
print(np.stack((a,b),axis=2))
# 垂直拼接
v1 = [[0,1,2,3,4,5],
   [6,7,8,9,10,11]]
v2 = [[12,13,14,15,16,17],
   [18,19,20,21,22,23]]
result  = np.vstack((v1,v2))
print(result)
print("-"*50)
result = np.hstack((v1,v2))
print(result)
# 数组分割
arr = np.arange(9).reshape(3,3)
print(np.split(arr,3,axis=0))
print("-"*50)
print(np.split(arr,3,axis=1))

# 数组的inf和nan
a = np.inf
b = np.nan
print(a,type(a))
print(b,type(b))
t = np.arange(24,dtype=np.float32).reshape(4,6)
t[3,4]=np.nan
print(t)
print(np.count_nonzero(t!=t))
t[np.isnan(t)] = 0

--------------------------------------------------
[[1 2 5 6]
 [3 4 7 8]]
--------------------------------------------------
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
--------------------------------------------------
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------------------------------------
[[ 0  1  2  3  4  5 12 13 14 15 16 17]
 [ 6  7  8  9 10 11 18 19 20 21 22 23]]
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]
--------------------------------------------------
[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]
inf <class 'float'>
nan <class 'float'>
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. nan 23.]]
1


In [12]:
import numpy as np
#处理数组中的nan
t = np.arange(24).reshape(4,6).astype('float')
t[1,3:]=np.nan
print(t)
print("-"*50)
for i in range(t.shape[1]):
    arr_col = t[:,i]
    nan_count = np.count_nonzero(arr_col!=arr_col)
    if nan_count:
        # 拿出不为nan的数据
       temp_col_not_nan = arr_col[arr_col == arr_col]
        # 赋为均值
       arr_col[np.isnan(arr_col)]= np.mean(temp_col_not_nan)
print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
--------------------------------------------------
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. 13. 14. 15.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


二维数组转置

In [18]:
# 转置数组
a = np.arange(12).reshape(3,4)
print(np.transpose(a))
print("-"*50)

t1 = np.arange(24).reshape(4,6)
print(t1.swapaxes(1,0))
print("-"*50)


#3维及以上的swapaxes
t=np.ones((3,4,5,6))
print(np.rollaxis(t,3,1))

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
--------------------------------------------------
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]
--------------------------------------------------
[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.

numpy 读取数据

In [5]:
import numpy as np
from matplotlib import pyplot as plt
uk_file_path = "./GBvideos.csv"
us_file_path = "./USvideos.csv"
t_uk=np.loadtxt(uk_file_path,delimiter=',',dtype='int')
plt.figure(figsize=(20,8),dpi=80)

t_uk_like = t_uk[:,1]
t_uk_comment = t_uk[-1,:]
plt.scatter(t_uk_like,t_uk_comment)
plt.show()
np.savetxt("like.csv",t_uk_like,delimiter=',')

ValueError: could not convert string to float: 'views'

In [10]:
a = np.array([1,2,3])
b = a.copy()
a[0] = 10
print(b)
print(a)

[1 2 3]
[10  2  3]
