In [14]:
import pandas as pd

series

In [9]:
ser_arr = pd.Series(range(10,20))
print(ser_arr)
print("-"*50)
print(ser_arr.index)
print("-"*50)
print(ser_arr.values)
print("-"*50)
ser_arr.dtype

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64
--------------------------------------------------
RangeIndex(start=0, stop=10, step=1)
--------------------------------------------------
[10 11 12 13 14 15 16 17 18 19]
--------------------------------------------------


dtype('int64')

In [11]:
print(ser_arr>15)

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool


In [13]:
# 字典变series
ser_dict = {2001: 17.8, 2005: 20.1, 2003: 16.5}
ser_arr1 = pd.Series(ser_dict)
print(ser_arr1)
print(ser_arr1.index)

2001    17.8
2005    20.1
2003    16.5
dtype: float64
Int64Index([2001, 2005, 2003], dtype='int64')


dataFrame  生成表格形状的二维数据结构

In [20]:
import numpy as np
t = pd.DataFrame(np.arange(12).reshape(3,4))
print(t)
print("-"*50)
#
arr = np.random.randn(5,4)
print(arr)
print("-"*50)
data_arr = pd.DataFrame(arr)
print("-"*50)
data_arr.head(3)

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
--------------------------------------------------
[[-0.82476139  0.97274807  0.97328274  0.19471659]
 [ 1.21565908  0.27911873  0.93724058  0.45470778]
 [ 0.46578771  2.25578566 -0.36445197  0.3449799 ]
 [ 2.35956124 -0.71867446 -1.95579166 -0.33926149]
 [ 1.4773572  -0.81824308  1.69992441 -0.23599279]]
--------------------------------------------------
--------------------------------------------------


0         1         2         3
0 -0.824761  0.972748  0.973283  0.194717
1  1.215659  0.279119  0.937241  0.454708
2  0.465788  2.255786 -0.364452  0.344980

In [22]:
d2 =[{"name" : "xiaohong" ,"age" :32,"tel" :10010},
     { "name": "xiaogang" ,"tel": 10000} ,
     {"name":"xiaowang" ,"age":22}]
arr  = pd.DataFrame(d2)
print(arr)
print("-"*50)
print(arr.values)

       name   age      tel
0  xiaohong  32.0  10010.0
1  xiaogang   NaN  10000.0
2  xiaowang  22.0      NaN
--------------------------------------------------
[['xiaohong' 32.0 10010.0]
 ['xiaogang' nan 10000.0]
 ['xiaowang' 22.0 nan]]


dataFrame 同一列必须同一数据类型

In [28]:
dict_data = {'A': 1,
             'B': pd.Timestamp('20190926'),
             'C': pd.Series(1, index=list(range(4)),dtype='float32'),
             'D': np.array([1,2,3,4],dtype='int32'),
             'E': ["Python","Java","C++","C"],
             'F': 'wangdao' }
data_obj2 = pd.DataFrame(dict_data)
print(data_obj2)
print("-"*50)
print(data_obj2.index)
print("-"*50)
print(data_obj2.columns)

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao
--------------------------------------------------
Int64Index([0, 1, 2, 3], dtype='int64')
--------------------------------------------------
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')


In [49]:
# 日期
dates = pd.date_range('20130101', periods=6)
print(dates)
data_arr=pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
print(data_arr)
# loc 取dataFrame中的元素
print(data_arr.loc['2013-01-01':'2013-01-03','A':'C'])
# iloc左闭右开
print(data_arr.iloc[0:2,0:2])

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
                   A         B         C         D
2013-01-01 -0.888765  0.435785  0.122424  1.939632
2013-01-02 -0.984260  1.216124 -0.121393  0.733263
2013-01-03 -1.290089 -1.633896  0.567004  0.274171
2013-01-04  1.547096  0.800204  0.124670  0.978139
2013-01-05  0.099154 -0.206278 -1.022136  1.221444
2013-01-06  0.084285 -1.479118 -1.654878 -1.872410
                   A         B         C
2013-01-01 -0.888765  0.435785  0.122424
2013-01-02 -0.984260  1.216124 -0.121393
2013-01-03 -1.290089 -1.633896  0.567004
                   A         B
2013-01-01 -0.888765  0.435785
2013-01-02 -0.984260  1.216124


In [48]:
ser_obj = pd.Series(range(5), index = list("abcde"))
t1 = pd.DataFrame(ser_obj)
print(t1)

   0
a  0
b  1
c  2
d  3
e  4


In [68]:
import numpy as np
df1 = pd.DataFrame(np.ones((2,2)), columns = ['a', 'b'])
df2 = pd.DataFrame(np.ones((3,3)), columns = ['a', 'b', 'c'])

print(df1)
print(d2)

# 未对齐的数据和值填充2
print(df1.sub(df2, fill_value = 2))

     a    b
0  1.0  1.0
1  1.0  1.0
[{'name': 'xiaohong', 'age': 32, 'tel': 10010}, {'name': 'xiaogang', 'tel': 10000}, {'name': 'xiaowang', 'age': 22}]
     a    b    c
0  0.0  0.0  1.0
1  0.0  0.0  1.0
2  1.0  1.0  1.0


pandas函数应用

In [73]:
# apply应用到每一列
df = pd.DataFrame(np.random.randn(5,4)-1)
print(df)
print(df.apply(lambda x:x.max(),axis=1))
# applymap应用到某每个数据
print("-"*50)
print(df.applymap(lambda x :'%.2f'%x))
df.dtypes

          0         1         2         3
0 -1.936983  0.711179 -0.830259 -2.746939
1  0.007741 -2.724129 -1.678752 -1.745642
2 -0.438174 -1.909966 -0.819335 -0.393137
3 -1.981561 -0.852695 -0.020737 -2.381391
4  0.222622  0.777435  0.535949 -0.666871
0    0.711179
1    0.007741
2   -0.393137
3   -0.020737
4    0.777435
dtype: float64
--------------------------------------------------
       0      1      2      3
0  -1.94   0.71  -0.83  -2.75
1   0.01  -2.72  -1.68  -1.75
2  -0.44  -1.91  -0.82  -0.39
3  -1.98  -0.85  -0.02  -2.38
4   0.22   0.78   0.54  -0.67


0    float64
1    float64
2    float64
3    float64
dtype: object

索引排序

In [84]:
s4 = pd.Series(range(10, 15), index = np.random.randint(5, size=5))
print(s4)
s4.sort_index
print(s4)
print(s4.iloc[0:3])
s4[0:3]
print("-"*50)
print(s4.sort_index(axis=0,ascending=False))
print("-"*50)

2    10
0    11
1    12
4    13
3    14
dtype: int64
2    10
0    11
1    12
4    13
3    14
dtype: int64
2    10
0    11
1    12
dtype: int64
--------------------------------------------------
4    13
3    14
2    10
1    12
0    11
dtype: int64
--------------------------------------------------


按值排序

In [87]:
import random
l=[random.randint(0,100) for i in range(24)]
df4 = pd.DataFrame(np.array(l).reshape(6,4))
print('-'*50)
print(df4)
print('-'*50)
print(df4.sort_values(by=3,ascending=False,axis=0))
print('-'*50)
print(df4.sort_values(axis=1,ascending=False,by=1))

--------------------------------------------------
    0   1   2   3
0  49  80   9  86
1  35  50  77  69
2  44  98  83  23
3  56  47  64  50
4  31  80  47  69
5  83  74  47  18
--------------------------------------------------
    0   1   2   3
0  49  80   9  86
1  35  50  77  69
4  31  80  47  69
3  56  47  64  50
2  44  98  83  23
5  83  74  47  18
--------------------------------------------------
    2   3   1   0
0   9  86  80  49
1  77  69  50  35
2  83  23  98  44
3  64  50  47  56
4  47  69  80  31
5  47  18  74  83


In [32]:
df_data = pd.DataFrame([np.random.randn(3), [1., 2., np.nan],
                       [np.nan, 4., np.nan], [1., 2., 3.]])
print(df_data.isnull()) # 布尔类型

       0      1      2
0  False  False  False
1  False  False   True
2   True  False   True
3  False  False  False


In [ ]:
print("-"*50)
print(df_data.dropna)
print("-"*50)
# 某列有nan就删除
print(df_data.dropna(axis=1))
print("-"*50)

In [95]:
# 空值填为0
print(df_data.iloc[:,1].fillna(-100.))

0   -0.331998
1    2.000000
2    4.000000
3    2.000000
Name: 1, dtype: float64


层级索引

In [6]:
import pandas as pd
import numpy as np
index1 = pd.MultiIndex.from_arrays([['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'c', 'd', 'd', 'd'],
                [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]],names=['cloth', 'size'])
ser_obj = pd.Series(np.random.randn(12),index = index1)
print(ser_obj)
print("-"*50)
print(type(ser_obj))
print("-"*50)
print(ser_obj.index)
print("-"*50)
print(ser_obj.values)
print("-"*50)
print(ser_obj.index.levels)

cloth  size
a      0      -0.147771
       1      -0.359634
       2       0.283622
b      0       0.864279
       1       0.430420
       2      -2.231459
c      0      -0.904635
       1       0.584289
       2      -0.549254
d      0       0.965699
       1      -0.371488
       2      -1.806374
dtype: float64
--------------------------------------------------
<class 'pandas.core.series.Series'>
--------------------------------------------------
MultiIndex([('a', 0),
            ('a', 1),
            ('a', 2),
            ('b', 0),
            ('b', 1),
            ('b', 2),
            ('c', 0),
            ('c', 1),
            ('c', 2),
            ('d', 0),
            ('d', 1),
            ('d', 2)],
           names=['cloth', 'size'])
--------------------------------------------------
[-0.1477712  -0.35963373  0.28362233  0.8642792   0.43041971 -2.23145897
 -0.9046353   0.58428857 -0.54925373  0.96569942 -0.37148762 -1.80637383]
------------------------------------------------

In [58]:
print(ser_obj.swaplevel())
print("-"*50)
#  level=最里面索引为-1
print(ser_obj.sort_index(level=-1))
# 索引0竖变横，打散堆
def_obj=ser_obj.unstack()
print("-"*50)
print(def_obj)

size  cloth
0     a       -0.147771
1     a       -0.359634
2     a        0.283622
0     b        0.864279
1     b        0.430420
2     b       -2.231459
0     c       -0.904635
1     c        0.584289
2     c       -0.549254
0     d        0.965699
1     d       -0.371488
2     d       -1.806374
dtype: float64
--------------------------------------------------
cloth  size
a      0      -0.147771
b      0       0.864279
c      0      -0.904635
d      0       0.965699
a      1      -0.359634
b      1       0.430420
c      1       0.584289
d      1      -0.371488
a      2       0.283622
b      2      -2.231459
c      2      -0.549254
d      2      -1.806374
dtype: float64
--------------------------------------------------
size          0         1         2
cloth                              
a     -0.147771 -0.359634  0.283622
b      0.864279  0.430420 -2.231459
c     -0.904635  0.584289 -0.549254
d      0.965699 -0.371488 -1.806374


In [30]:
# 堆叠
def_obj.stack()

cloth  size
a      0      -0.147771
       1      -0.359634
       2       0.283622
b      0       0.864279
       1       0.430420
       2      -2.231459
c      0      -0.904635
       1       0.584289
       2      -0.549254
d      0       0.965699
       1      -0.371488
       2      -1.806374
dtype: float64

# pandas统计与计算

In [34]:
def_obj['0','b']=np.nan
print(def_obj)
print("-"*50)
print(def_obj.min(axis=0,skipna=True))
print("-"*50)
print(def_obj.describe()) # 观察数据分布的一中方法

size          0         1         2  (0, b)
cloth                                      
a     -0.147771 -0.359634  0.283622     NaN
b      0.864279  0.430420 -2.231459     NaN
c     -0.904635  0.584289 -0.549254     NaN
d      0.965699 -0.371488 -1.806374     NaN
--------------------------------------------------
size
0        -0.904635
1        -0.371488
2        -2.231459
(0, b)         NaN
dtype: float64
--------------------------------------------------
size          0         1         2  (0, b)
count  4.000000  4.000000  4.000000     0.0
mean   0.194393  0.070897 -1.075866     NaN
std    0.888557  0.507900  1.153916     NaN
min   -0.904635 -0.371488 -2.231459     NaN
25%   -0.336987 -0.362597 -1.912645     NaN
50%    0.358254  0.035393 -1.177814     NaN
75%    0.889634  0.468887 -0.341035     NaN
max    0.965699  0.584289  0.283622     NaN


In [26]:
def_obj.loc[:,'c']

KeyError: 'c'

KeyError: 'c'

In [24]:
# print(def_obj.loc[:,'c'].argmin())
# argmin和argmax只能是series,不能是df

KeyError: 'c'

KeyError: 'c'

In [35]:
# 返回的是一个series
def_obj.idxmin(axis=1)

cloth
a    1
b    2
c    0
d    2
dtype: int64

In [ ]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
file_path = "IMDB-Movie-Data.csv"
df = pd.read_csv(file_path)
print(df.info)
print(df.describe())
print('-'*50)
print(len(df['Director'].tolist()))
print(len(df['Director'].unique()))
# 获取演员人数
# 二维列表
team_actors_list=df['Actors'].str.split(", ").tolist()
genre_list = list[set([i for j in team_actors_list for i in j])]
actors_num = len(set(genre_list))
# 构造全为0的数组
zeros_df=pd.DataFrame(np.zeros((df.shape[0],len(genre_list))),columns=genre_list)

print(zeros_df)

pandas 分组与聚合

In [52]:
import pandas as pd
import numpy as np
dict_obj = {'key1' : ['a', 'b', 'a', 'b',
                      'a', 'b', 'a', 'a'],
            'key2' : ['one', 'one', 'two', 'three',
                      'two', 'two', 'one', 'three'],
            'data1': np.random.randn(8),
            'data2': np.random.randn(8)}
print(pd.DataFrame(dict_obj))
print("-"*50)

df = pd.DataFrame(dict_obj)
print(df.groupby('key1'))
print("-"*50)
print(type(df.groupby('key2')))
print("-"*50)
print(df)
print(type(df['data1'].groupby(df['key1'])))
print("-"*50)
group1 = df.groupby('key1')
print(group1.mean())

  key1   key2     data1     data2
0    a    one  1.763084 -0.006598
1    b    one -0.335862 -0.267240
2    a    two  1.009256  1.358195
3    b  three  0.095271  2.531286
4    a    two  1.204176  0.705382
5    b    two  1.861114 -1.270413
6    a    one  0.754356  0.488364
7    a  three -0.480100  0.620591
--------------------------------------------------
--------------------------------------------------
<class 'pandas.core.groupby.generic.DataFrameGroupBy'>
--------------------------------------------------
  key1   key2     data1     data2
0    a    one  1.763084 -0.006598
1    b    one -0.335862 -0.267240
2    a    two  1.009256  1.358195
3    b  three  0.095271  2.531286
4    a    two  1.204176  0.705382
5    b    two  1.861114 -1.270413
6    a    one  0.754356  0.488364
7    a  three -0.480100  0.620591
<class 'pandas.core.groupby.generic.SeriesGroupBy'>
--------------------------------------------------
         data1     data2
key1                    
a     0.850154  0.633187
b 

自定义分组

In [80]:
self_def_key = [0, 1, 2, 3, 3, 3, 5, 7]
print(df.groupby(self_def_key).size()) #分组后求大小数目
print(df.groupby(self_def_key).sum())
print("-"*50)
# 多层列表
print(df.groupby([df['key1'],df['key2']]).size())
print("-"*50)
grouped3 = df.groupby(['key2', 'key1'])
print(grouped3.mean())
print(grouped3.mean().index)
print("-"*50)
print(grouped3.mean().unstack())

0    1
1    1
2    1
3    3
5    1
7    1
dtype: int64
      data1     data2
0  1.763084 -0.006598
1 -0.335862 -0.267240
2  1.009256  1.358195
3  3.160561  1.966256
5  0.754356  0.488364
7 -0.480100  0.620591
--------------------------------------------------
key1  key2 
a     one      2
      three    1
      two      2
b     one      1
      three    1
      two      1
dtype: int64
--------------------------------------------------
               data1     data2
key2  key1                    
one   a     1.258720  0.240883
      b    -0.335862 -0.267240
three a    -0.480100  0.620591
      b     0.095271  2.531286
two   a     1.106716  1.031789
      b     1.861114 -1.270413
MultiIndex([(  'one', 'a'),
            (  'one', 'b'),
            ('three', 'a'),
            ('three', 'b'),
            (  'two', 'a'),
            (  'two', 'b')],
           names=['key2', 'key1'])
--------------------------------------------------
          data1               data2          
key1         

In [81]:
list(grouped3)

[(('one', 'a'),
    key1 key2     data1     data2
  0    a  one  1.763084 -0.006598
  6    a  one  0.754356  0.488364),
 (('one', 'b'),
    key1 key2     data1    data2
  1    b  one -0.335862 -0.26724),
 (('three', 'a'),
    key1   key2   data1     data2
  7    a  three -0.4801  0.620591),
 (('three', 'b'),
    key1   key2     data1     data2
  3    b  three  0.095271  2.531286),
 (('two', 'a'),
    key1 key2     data1     data2
  2    a  two  1.009256  1.358195
  4    a  two  1.204176  0.705382),
 (('two', 'b'),
    key1 key2     data1     data2
  5    b  two  1.861114 -1.270413)]

In [85]:
# 按类型分组
df['data3'] = df['data2']+1
print(df)
print(df.groupby(df.dtypes,axis=1).size())
print("-"*50)
self_column_key=[1,2,3,3,4]
# 自定义不同的列相加
print(df.groupby(self_column_key,axis=1).sum())

  key1   key2     data1     data2     data3
0    a    one  1.763084 -0.006598  0.993402
1    b    one -0.335862 -0.267240  0.732760
2    a    two  1.009256  1.358195  2.358195
3    b  three  0.095271  2.531286  3.531286
4    a    two  1.204176  0.705382  1.705382
5    b    two  1.861114 -1.270413 -0.270413
6    a    one  0.754356  0.488364  1.488364
7    a  three -0.480100  0.620591  1.620591
float64    3
object     2
dtype: int64
--------------------------------------------------
   1      2         3         4
0  a    one  1.756486  0.993402
1  b    one -0.603102  0.732760
2  a    two  2.367452  2.358195
3  b  three  2.626557  3.531286
4  a    two  1.909559  1.705382
5  b    two  0.590701 -0.270413
6  a    one  1.242720  1.488364
7  a  three  0.140491  1.620591


聚合

In [8]:
import numpy as np
import pandas as pd
dict_obj = {'key1' : ['a', 'b', 'a', 'b',
                      'a', 'b', 'a', 'a'],
            'key2' : ['one', 'one', 'two', 'three',
                      'two', 'two', 'one', 'three'],
            'data1': np.random.randint(1,10, 8),
            'data2': np.random.randint(1,10, 8)}
df_obj = pd.DataFrame(dict_obj)
print('-'*50)
print(df_obj.groupby('key1').sum())
print(df_obj.groupby("key1").max())
print('-'*50)
# 平均值
print(df_obj.groupby('key1').describe())
print('-'*50)
def peak_range(func):
    return func.max() - func.min()
print(df_obj.loc[:,['key1','data1','data2']].groupby('key1').agg(peak_range))

--------------------------------------------------
      data1  data2
key1              
a        26     11
b        14     21
     key2  data1  data2
key1                   
a     two      7      4
b     two      5      9
--------------------------------------------------
     data1                                             data2                 \
     count      mean      std  min  25%  50%  75%  max count mean       std   
key1                                                                          
a      5.0  5.200000  2.48998  2.0  3.0  7.0  7.0  7.0   5.0  2.2  1.303840   
b      3.0  4.666667  0.57735  4.0  4.5  5.0  5.0  5.0   3.0  7.0  3.464102   

                               
      min  25%  50%  75%  max  
key1                           
a     1.0  1.0  2.0  3.0  4.0  
b     3.0  6.0  9.0  9.0  9.0  
--------------------------------------------------
      data1  data2
key1              
a         5      3
b         1      6


同时应用多个聚合函数

In [13]:
print(df_obj.groupby('key1').agg(['mean','count','std',peak_range]))

         data1                           data2                           
          mean count      std peak_range  mean count       std peak_range
key1                                                                     
a     5.200000     5  2.48998          5   2.2     5  1.303840          3
b     4.666667     3  0.57735          1   7.0     3  3.464102          6


In [15]:
# 每一列应用不同的聚合函数
dict_func={'data1':'mean','data2':'max'}
df_obj.groupby('key1').agg(dict_func)

data1  data2
key1                 
a     5.200000      4
b     4.666667      9

时间序列

In [18]:
pd.date_range(start="20190101", end="20190924")
print("-"*50)
pd.date_range(start='20210712',periods=6,freq='B')

--------------------------------------------------


DatetimeIndex(['2021-07-12', '2021-07-13', '2021-07-14', '2021-07-15',
               '2021-07-16', '2021-07-19'],
              dtype='datetime64[ns]', freq='B')

In [19]:
print(pd.date_range('20210712',periods=10,freq='M'))

DatetimeIndex(['2021-07-31', '2021-08-31', '2021-09-30', '2021-10-31',
               '2021-11-30', '2021-12-31', '2022-01-31', '2022-02-28',
               '2022-03-31', '2022-04-30'],
              dtype='datetime64[ns]', freq='M')


In [21]:
s = pd.Series(['3/11/2000', '3/12/2000', '3/13/2000'] * 1000)
s

0       3/11/2000
1       3/12/2000
2       3/13/2000
3       3/11/2000
4       3/12/2000
          ...    
2995    3/12/2000
2996    3/13/2000
2997    3/11/2000
2998    3/12/2000
2999    3/13/2000
Length: 3000, dtype: object

降采样

In [32]:
idx = pd.date_range('1/1/2000', periods=4, freq='T')
df = pd.DataFrame(data=4 * [range(2)],
                  index=idx,
                  columns=['a', 'b'])
print(df)
print("-"*50)
df.groupby('a').resample('3T').sum()
print("-"*50)
df.groupby('b').resample('30s').sum()
k1_sum = df.groupby('key1').sum().add_suffix('sum_')
print(k1_sum)


                     a  b
2000-01-01 00:00:00  0  1
2000-01-01 00:01:00  0  1
2000-01-01 00:02:00  0  1
2000-01-01 00:03:00  0  1
--------------------------------------------------
--------------------------------------------------


NameError: name 'df_data' is not defined

In [5]:
import  pandas as pd
import  numpy as np
df_obj1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                        'data1' : np.random.randint(0,10,7)})
df_obj2 = pd.DataFrame({'key': ['a', 'b' ,'d'],
                        'data2' : np.random.randint(0,10,3)})
# 表连接
pd.merge(df_obj1,df_obj2,on='key')
df_obj1=df_obj1.rename(columns={'key':'key1'})
df_obj2=df_obj2.rename(columns={'key':'key2'})
print(df_obj1)
print(df_obj2)
print("-"*50)
# 左表key1,右表key2
pd.merge(df_obj1,df_obj2,left_on='key1',right_on='key2')

  key1  data1
0    b      1
1    b      9
2    a      2
3    c      9
4    a      8
5    a      4
6    b      0
  key2  data2
0    a      7
1    b      4
2    d      9
--------------------------------------------------


key1  data1 key2  data2
0    b      1    b      4
1    b      9    b      4
2    b      0    b      4
3    a      2    a      7
4    a      8    a      7
5    a      4    a      7

In [8]:
df_obj1
df_obj2
print("-"*50)
#全外连接
pd.merge(df_obj1, df_obj2, left_on='key1',right_on='key2',how='outer')

--------------------------------------------------


key1  data1 key2  data2
0    b    1.0    b    4.0
1    b    9.0    b    4.0
2    b    0.0    b    4.0
3    a    2.0    a    7.0
4    a    8.0    a    7.0
5    a    4.0    a    7.0
6    c    9.0  NaN    NaN
7  NaN    NaN    d    9.0

In [10]:
# right等价于数据库的right on
pd.merge(df_obj1, df_obj2, left_on='key1', right_on='key2', how='left')

key1  data1 key2  data2
0    b      1    b    4.0
1    b      9    b    4.0
2    a      2    a    7.0
3    c      9  NaN    NaN
4    a      8    a    7.0
5    a      4    a    7.0
6    b      0    b    4.0

In [11]:
pd.merge(df_obj1,df_obj2,left_on='key1',right_on='key2',how='right')

key1  data1 key2  data2
0    a    2.0    a      7
1    a    8.0    a      7
2    a    4.0    a      7
3    b    1.0    b      4
4    b    9.0    b      4
5    b    0.0    b      4
6  NaN    NaN    d      9

In [13]:
# 处理重复列名
df_obj1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                        'data' : np.random.randint(0,10,7)})
df_obj2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                        'data' : np.random.randint(0,10,3)})
# 给相同的数据列添加后缀
print(pd.merge(df_obj1,df_obj2,on='key',suffixes=('_left','_right')))

  key  data_left  data_right
0   b          0           4
1   b          7           4
2   b          6           4
3   a          6           5
4   a          1           5
5   a          4           5


In [19]:
# 按索引连接
df_obj1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                        'data1' : np.random.randint(0,10,7)})
df_obj2 = pd.DataFrame({'data2' : np.random.randint(0,10,3)}, index=['a', 'b', 'd'])
print(df_obj1)
print(df_obj2)
print("-"*50)
print(pd.merge(df_obj1,df_obj2,left_on='key',right_index=True))
print("-"*50)
print(pd.merge(df_obj2,df_obj1,right_on='key',left_index=True))

  key  data1
0   b      7
1   b      3
2   a      1
3   c      9
4   a      8
5   a      3
6   b      5
   data2
a      6
b      6
d      4
--------------------------------------------------
  key  data1  data2
0   b      7      6
1   b      3      6
6   b      5      6
2   a      1      6
4   a      8      6
5   a      3      6
--------------------------------------------------
   data2 key  data1
2      6   a      1
4      6   a      8
5      6   a      3
0      6   b      7
1      6   b      3
6      6   b      5


数据合并

In [22]:
arr1 = np.random.randint(0,10,(3,4))
arr2 = np.random.randint(0,10,(3,4))
print(arr1)
print(arr2)

print(np.concatenate([arr1,arr2],axis=1))

[[5 9 4 0]
 [3 8 7 8]
 [3 9 0 6]]
[[1 9 7 9]
 [4 3 2 7]
 [5 6 3 5]]
[[5 9 4 0 1 9 7 9]
 [3 8 7 8 4 3 2 7]
 [3 9 0 6 5 6 3 5]]


In [23]:
ser_obj1 = pd.Series(np.random.randint(0, 10, 5), index=range(0,5))
ser_obj2 = pd.Series(np.random.randint(0, 10, 4), index=range(5,9))
ser_obj3 = pd.Series(np.random.randint(0, 10, 3), index=range(9,12))
print(ser_obj1)
print(ser_obj2)
print(ser_obj3)

0    8
1    3
2    6
3    3
4    3
dtype: int32
5    1
6    9
7    8
8    6
dtype: int32
9     0
10    5
11    0
dtype: int32


In [25]:
print(pd.concat([ser_obj1,ser_obj2,ser_obj3],axis=1))

      0    1    2
0   8.0  NaN  NaN
1   3.0  NaN  NaN
2   6.0  NaN  NaN
3   3.0  NaN  NaN
4   3.0  NaN  NaN
5   NaN  1.0  NaN
6   NaN  9.0  NaN
7   NaN  8.0  NaN
8   NaN  6.0  NaN
9   NaN  NaN  0.0
10  NaN  NaN  5.0
11  NaN  NaN  0.0


有重复的情况
# index

In [26]:
ser_obj1 = pd.Series(np.random.randint(0, 10, 5), index=range(5))
ser_obj2 = pd.Series(np.random.randint(0, 10, 4), index=range(4))
ser_obj3 = pd.Series(np.random.randint(0, 10, 3), index=range(3))
print(ser_obj1)
print(ser_obj2)
print(ser_obj3)

0    9
1    3
2    6
3    3
4    2
dtype: int32
0    7
1    1
2    7
3    3
dtype: int32
0    2
1    9
2    1
dtype: int32


In [27]:
# 相同索引名直接下滑
print(pd.concat([ser_obj1,ser_obj2,ser_obj3]))

0    9
1    3
2    6
3    3
4    2
0    7
1    1
2    7
3    3
0    2
1    9
2    1
dtype: int32


In [28]:
# inner和outer代表内连接和外连接
print(pd.concat([ser_obj1,ser_obj2,ser_obj3],axis=1,join='inner'))

   0  1  2
0  9  7  2
1  3  1  9
2  6  7  1


df的concat

In [29]:
import pandas as pd
import numpy as np
df_obj1 = pd.DataFrame(np.random.randint(0, 10, (3, 2)), index=['a', 'b', 'c'],
                       columns=['A', 'B'])
df_obj2 = pd.DataFrame(np.random.randint(0, 10, (2, 2)), index=['a', 'b'],
                       columns=['A', 'B'])
print(pd.concat([df_obj1,df_obj2],axis=1))

   A  B
a  1  1
b  4  9
c  7  3
a  5  1
b  3  6


### 数据重构

In [33]:
df_obj = pd.DataFrame(np.random.randint(0,10, (5,2)), columns=['data1', 'data2'])
print(df_obj)
print("-"*50)
stacked = df_obj.stack()
#stack内部带的参数level，选择哪一个column变为index
print(stacked)

   data1  data2
0      3      7
1      4      4
2      8      6
3      0      4
4      8      0
--------------------------------------------------
0  data1    3
   data2    7
1  data1    4
   data2    4
2  data1    8
   data2    6
3  data1    0
   data2    4
4  data1    8
   data2    0
dtype: int32


In [34]:
print(stacked.unstack())
# 通过level指定操作索引的级别
print(stacked.unstack(level=1))

   data1  data2
0      3      7
1      4      4
2      8      6
3      0      4
4      8      0
   data1  data2
0      3      7
1      4      4
2      8      6
3      0      4
4      8      0


In [38]:
index1 = pd.MultiIndex.from_arrays([['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'c', 'd', 'd', 'd'],
                [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]], names=['cloth', 'size'])
df = pd.DataFrame(np.arange(24).reshape(12,2),index=index1,columns=['data1','data2'])
print(df)
print("-"*50)
df_s = df.unstack(level=0)
print("-"*50)
print(df.columns)
df_s.stack(0) #把columns上的0层索引放到index的内层索引

            data1  data2
cloth size              
a     0         0      1
      1         2      3
      2         4      5
b     0         6      7
      1         8      9
      2        10     11
c     0        12     13
      1        14     15
      2        16     17
d     0        18     19
      1        20     21
      2        22     23
--------------------------------------------------
--------------------------------------------------
Index(['data1', 'data2'], dtype='object')


cloth       a   b   c   d
size                     
0    data1  0   6  12  18
     data2  1   7  13  19
1    data1  2   8  14  20
     data2  3   9  15  21
2    data1  4  10  16  22
     data2  5  11  17  23

## 处理重复数据

In [ ]:
df_obj = pd.DataFrame({'data1' : ['a'] * 4 + ['b'] * 4,
                       'data2' : np.random.randint(0, 4, 8)})

print(df_obj)

In [40]:
print(df_obj.duplicated())
# 取出非重复行
df_obj[~df_obj.duplicated()]

0    False
1    False
2    False
3    False
4    False
dtype: bool


data1  data2
0      3      7
1      4      4
2      8      6
3      0      4
4      8      0

In [41]:
print(df_obj.duplicated('data2'))

0    False
1    False
2    False
3     True
4    False
dtype: bool


In [43]:
df_obj1 = pd.DataFrame({'data1' :[np.nan] * 4,
                       'data2' :list('1235')})
df_obj1

data1 data2
0    NaN     1
1    NaN     2
2    NaN     3
3    NaN     5

In [45]:
# 去除重复的NAN
df_obj1.duplicated('data1')
print(df_obj1.drop_duplicates('data1'))

   data1 data2
0    NaN     1


In [46]:
print(df_obj.drop_duplicates())  #删除重复行
print(df_obj.drop_duplicates('data2'))

   data1  data2
0      3      7
1      4      4
2      8      6
3      0      4
4      8      0
   data1  data2
0      3      7
1      4      4
2      8      6
4      8      0


In [51]:
ser_obj = pd.Series(np.random.randint(0,10,20))
print(ser_obj)
print("-"*50)
print(ser_obj.map(lambda x:x**2))

0     6
1     4
2     5
3     8
4     4
5     1
6     7
7     7
8     9
9     4
10    8
11    0
12    9
13    1
14    7
15    5
16    6
17    7
18    1
19    1
dtype: int32
0     36
1     16
2     25
3     64
4     16
5      1
6     49
7     49
8     81
9     16
10    64
11     0
12    81
13     1
14    49
15    25
16    36
17    49
18     1
19     1
dtype: int64


In [54]:
ser_obj = pd.Series(np.arange(10),index=range(3,13))
# 替换单个值
print(ser_obj.replace(1,-100))
print("-"*50)
# 替换多个值
print(ser_obj.replace([4,7],[-100,-200]))

3       0
4    -100
5       2
6       3
7       4
8       5
9       6
10      7
11      8
12      9
dtype: int32
--------------------------------------------------
3       0
4       1
5       2
6       3
7    -100
8       5
9       6
10   -200
11      8
12      9
dtype: int64


In [59]:
df = pd.DataFrame({'A': [0, 1, 2, 3, 4],
                   'B': [5, 6, 7, 8, 9],
                   'C': ['a', 'b', 'c', 'd', 'e']})
df

A  B  C
0  0  5  a
1  1  6  b
2  2  7  c
3  3  8  d
4  4  9  e

In [57]:
df.replace(to_replace=r'^a',value=100,regex=True)

A  B    C
0  0  5  100
1  1  6    b
2  2  7    c
3  3  8    d
4  4  9    e